services:
  - type: web
    name: pdf-license-server
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120 --keep-alive 5 --max-requests 1000"
    healthCheckPath: "/health"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: Admin
      - key: ADMIN_PASSWORD
        generateValue: true

databases:
  - name: pdf-license-db
    databaseName: pdf_licenses
    user: pdf_admin
    plan: free
