services:
  - type: web
    name: pdf-license-server
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers 1 --bind 0.0.0.0:$PORT --timeout 120"
    healthCheckPath: "/health"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: Admin
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        value: your_username/pdf-license-server
      - key: GITHUB_BRANCH
        value: main

databases:
  - name: pdf-license-db
    databaseName: pdf_licenses
    user: pdf_admin
    plan: free
