services:
  - type: web
    name: pdf-license-server
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn server:app --workers 1 --bind 0.0.0.0:$PORT --timeout 120"
    healthCheckPath: "/health"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: Admin
      - key: ADMIN_PASSWORD
        generateValue: true
  
  - type: web
    name: pdf-metadata-app
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers 1 --bind 0.0.0.0:$PORT --timeout 120"
    healthCheckPath: "/health"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: LICENSE_SERVER_URL
        value: https://pdf-license-server-dmyx.onrender.com

databases:
  - name: pdf-license-db
    databaseName: pdf_licenses
    user: pdf_admin
    plan: free
